---
- hosts: all
  gather_facts: no
  connection: local
  vars_files:
    - ./cil-vault.yml
  vars:
    - domain_name: ciscolabs.net

  tasks:
    # authenticate using email and API token
    - debug: msg="Adding {{ inventory_hostname }} with address {{ ansible_ssh_host }}"
    - local_action: dnsimple account_email="{{ dnsimple_email }}" account_api_token="{{ dnsimple_token }}" domain="{{ domain_name }}" record="{{ inventory_hostname }}" type=A value="{{ ansible_ssh_host }}" state=present
