---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    instance_dict: {}
    subnet_dict: {}
    security_group_dict: {}
  vars_files:
    - clus-vars.yml

  tasks:
    - include: ../cloud/{{ regions[region_item].provider }}-region.yml
      vars:
        - region_name: "{{ region_item }}"
        - region_data: "{{ regions[region_item] }}"
        - acl_data: "{{ acl_dict }}"
        - ssh_key_data: "{{ ssh_keys }}"
      with_items: "{{ regions.keys() | default([]) }}"
      loop_control:
        loop_var: region_item
      tags:
        - cloud
