---
- hosts: tag_Role_dmvpn_spoke
  gather_facts: no
  connection: local
  vars_files:
    - clus-vars.yml

  tasks:
    - name: Set the Region Name
      set_fact: region_name="{{ hostvars[inventory_hostname].ec2_region }}"

    - name: Parameter Munging
      set_fact:
        dmvpn_network_address: "{{ dmvpn_network_cidr | ipaddr('network') }}"
        dmvpn_host_mask: "{{ dmvpn_network_cidr | ipaddr('hostmask') }}"
        spoke_network_address: "{{ dmvpn_dict[region_name].inside_cidr | ipaddr('network') }}"
        spoke_host_mask: "{{ dmvpn_dict[region_name].inside_cidr | ipaddr('hostmask') }}"
        dmvpn_tunnel_address: "{{ dmvpn_dict[region_name].tunnel_ip | ipaddr('address') }}"
        dmvpn_tunnel_mask: "{{ dmvpn_dict[region_name].tunnel_ip | ipaddr('netmask') }}"

#    - debug: var=hostvars[inventory_hostname]

    - name: Get IOS Version
      ios_command:
        provider:
          host: "{{ inventory_hostname }}"
          username: ec2-user
        commands: show version | inc Cisco IOS XE Software
      register: command_results

    - debug: var=command_results.stdout_lines[0]

    - name: Configure as DMVPN Spoke
      ios_config:
        provider:
          host: "{{ inventory_hostname }}"
          username: ec2-user
        src: dmvpn_spoke.j2
      register: command_results