---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    instances:
      - { name: smc-host4, size: m1.medium, image: RHEL-guest-image, key_name: STEVENCA-M-202D, subnet: workshop-net1, tags: {ansible_group: smc} }
      - { name: smc-host5, size: m1.medium, image: RHEL-guest-image, key_name: STEVENCA-M-202D, subnet: workshop-net1, tags: {ansible_group: smc} }
      - { name: smc-host6, size: m1.medium, image: RHEL-guest-image, key_name: STEVENCA-M-202D, subnet: workshop-net1, tags: {ansible_group: smc} }


  tasks:

    - name: Create the OpenStack instance
      os_server:
        state: present
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        key_name: "{{ item.key_name }}"
        flavor: "{{ item.size }}"
        nics:
          - net-name: "{{ item.subnet }}"
        validate_certs: False
        meta: "{{ item.tags | default(omit) }}"
      with_items: "{{ instances | default([]) }}"
      tags:
        - instances