---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    os_flavors:
      - {name: m1.tiny, ram: 512, vcpus: 1, disk: 1, ephemeral: 0}
      - {name: m1.small, ram: 2048, vcpus: 1, disk: 20, ephemeral: 0}
      - {name: m1.medium, ram: 4096, vcpus: 2, disk: 40, ephemeral: 0}
      - {name: m1.large, ram: 8192, vcpus: 4, disk: 80, ephemeral: 0}
      - {name: m1.xlarge, ram: 16384, vcpus: 8, disk: 160, ephemeral: 0}


  tasks:
    - name: Create Flavors
      os_nova_flavor:
        cloud: wopr
        validate_certs: no
        state: present
        name: "{{ item.name }}"
        ram: "{{ item.ram }}"
        vcpus: "{{ item.vcpus }}"
        disk: "{{ item.disk }}"
        ephemeral: "{{ item.ephemeral }}"
      with_items: "{{ os_flavors }}"